// Operator (ATOC) codes used in the timetable, mapped to the names passengers know.
const OPERATORS: Record<string, string> = {
  AW: 'Transport for Wales',
  CC: 'c2c',
  CH: 'Chiltern Railways',
  CS: 'Caledonian Sleeper',
  EM: 'East Midlands Railway',
  ES: 'Eurostar',
  GC: 'Grand Central',
  GN: 'Great Northern',
  GR: 'LNER',
  GW: 'GWR',
  GX: 'Gatwick Express',
  HT: 'Hull Trains',
  HX: 'Heathrow Express',
  IL: 'Island Line',
  LD: 'Lumo',
  LE: 'Greater Anglia',
  LM: 'West Midlands Railway',
  LO: 'London Overground',
  ME: 'Merseyrail',
  NT: 'Northern',
  SE: 'Southeastern',
  SN: 'Southern',
  SR: 'ScotRail',
  SW: 'South Western Railway',
  TL: 'Thameslink',
  TP: 'TransPennine Express',
  VT: 'Avanti West Coast',
  XC: 'CrossCountry',
  XR: 'Elizabeth line',
};

export const operatorName = (code: string) => OPERATORS[code] ?? code;
